log-level: debug
mixed-port: 7890
allow-lan: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-name: yacd
external-ui-url: "https://ghfast.top/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip"
unified-delay: true
tcp-concurrent: true
geodata-mode: true
geox-url:
  geoip: "https://ghfast.top/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://ghfast.top/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - geosite:cn
    - geosite:private
  respect-rules: true
  default-nameserver:
    - https://223.5.5.5/dns-query
    - https://120.53.53.53/dns-query
  nameserver:
    - https://dns.google/dns-query
  nameserver-policy:
    geosite:cn,private:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
proxies:
  - name: "✨ fcm"
    type: ss
    server: 45.62.119.122
    port: 9443
    cipher: 2022-blake3-aes-128-gcm
    password: "Vhk9Vt3YW7bgLJpAnKxK4w=="
    plugin: shadow-tls
    client-fingerprint: chrome
    plugin-opts:
      host: "board.zuoye.win"
      password: "R9vnbCLnYTtAitd"
      version: 3
    smux:
      enabled: true
      protocol: yamux
      max-connections: 1
      min-streams: 4
      padding: true
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - AUTO
  - name: AUTO
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 180
    tolerance: 50
    proxies:
  - name: AI
    type: select
    proxies:
      - PROXY
  - name: FCM
    type: select
    proxies:
      - ✨ fcm
      - PROXY
      - DIRECT
  - name: GOOGLE
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: HOYO
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: MICROSOFT
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: SPOTIFY
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: TIKTOK
    type: select
    proxies:
      - PROXY
  - name: UDP
    type: select
    proxies:
      - PROXY
      - DIRECT
rules:
  - GEOSITE,CATEGORY-ADS-ALL,REJECT
  - AND,((NETWORK,udp),(DST-PORT,443)),REJECT
  - DST-PORT,853,REJECT
  - GEOSITE,CATEGORY-AI-!CN,AI
  - GEOSITE,GOOGLEFCM,FCM
  - GEOSITE,GOOGLE,GOOGLE
  - GEOIP,GOOGLE,GOOGLE
  - DOMAIN-KEYWORD,public-operation-hkrpg-sg.hoyoverse.com,HOYO
  - DOMAIN-KEYWORD,public-operation-hk4e-sg.hoyoverse.com,HOYO
  - DOMAIN-KEYWORD,public-operation-nap-sg.hoyoverse.com,HOYO
  - DOMAIN-KEYWORD,autopatchhk.yuanshen.com,HOYO
  - DOMAIN-KEYWORD,autopatchos.starrails.com,HOYO
  - DOMAIN-KEYWORD,autopatchos.zenlesszonezero.com,HOYO
  - DST-PORT,23301/22101-22102/20501/21601-21606/21101,HOYO
  - GEOSITE,HOYOVERSE,PROXY
  - GEOSITE,MICROSOFT,MICROSOFT
  - GEOSITE,SPOTIFY,SPOTIFY
  - GEOSITE,TIKTOK,TIKTOK
  - GEOSITE,PRIVATE,DIRECT
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - NETWORK,udp,UDP
  - MATCH,PROXY