name: SubAutoUpdate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sub branch
        uses: actions/checkout@v4
        with:
          ref: sub

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24.0.1"

      - name: Download SubStore
        run: |
          python substore/update.py

      - name: Run processing scripts
        run: bash run_scripts.sh

      - name: Clean up substore folder
        run: |
          rm -f substore/root.json substore/"${{ vars.SUBSTORE }}"
          ls substore

      - name: Commit and push changes (if any)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Auto commit changes from GitHub Action"
            git push origin sub
          else
            echo "No changes to commit."
          fi